version: '3.8'
services:
  finotech_server:
    container_name: finotech_server
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - env/.development.env
    ports:
      - '5000:5000'
    volumes:
      - .:/app/
    depends_on:
      - finotech_postgres
      - finotech_redis
  finotech_postgres:
    image: postgres
    restart: always
    container_name: finotech_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: finotech
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
  finotech_redis:
    image: redis:alpine
    container_name: finotech_redis
    ports:
      - '6380:6379'
    restart: on-failure
    volumes:
      - redis-data:/data/
      - redis-conf:/usr/local/etc/redis/redis.conf
volumes:
  pg_data:
  redis-data:
  redis-conf:
